### ISSUE TITLE
After accessing the github link in the menu section about Polar Clock app. The back button can not be used or does not work

### ISSUE THREAD

**Issue by ammarraisafti** [beriain/PolarClock#10]
# Expected behavior 
When I access the github link in the About menu section. The link is an error and I can not go back on the previous menu.

# Actual behavior
I did it repeatedly, but did not make it back to the previous menu. The back button does not work. And the link available in the menu about Error.

# How to reproduce
Install the Polar Clock app. Run this app. click the shortcut at the top, then select the about menu. And after successfully enter the menu about. Click the github link provided. And you will get the problem as I have described, the link github error, and can not return to the previous menu, even if you do it repeatedly.

* Browser: Samsung galaxy S6 edge 
* Operating system: Nougat 7.0 
* App version: 1.4.2

# Recording Of The Bug
https://youtu.be/dRAz3By0Fcc
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@ammarraisafti/after-accessing-the-github-link-in-the-menu-section-about-polar-clock-app-the-back-button-can-not-be-used-or-does-not-work">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by beriain** [comment]
This was already fixed in 6a60b2b234d906228353cfa70da3c6fca9632432

I'm trying to finnish with #6 and a pair of things more before doing a new release.

**Comment by ammarraisafti** [comment]
Thank you very much for your prompt response, I am very happy to hear it.
And I hope the Polar Clock application is more optimal for future use. And
I will invite other users to download this application. Because you are
very quick to make improvements.

Pada tanggal Sab, 7 Apr 2018 14:44, Aitor Beriain <notifications@github.com>
menulis:
