### ISSUE TITLE
New logo proposal for Polar Clock app

### ISSUE THREAD

**Issue by ammarraisafti** [beriain/PolarClock#11]
Hi admin, I want to offer a simple new logo design for Polar Clock application. This logo is my special design for you. If you are willing to accept it, you simply reply to this proposal. I will send you a new logo of this file. And if you want other color variations or some additional icon in it. You can tell me. I will update it soon. Thanks

![polar clock](https://user-images.githubusercontent.com/37721970/41494291-3ff5f8fe-713b-11e8-8c0a-e3f3e5c2421a.png)

**Comment by beriain** [comment]
Thank you for your proposal, I really appreciate your effort, but I'm actually happy with the current icon and I i'm not thinking in changing it in the short term.
