### ISSUE TITLE
Bug foung on Settings Button 

### ISSUE THREAD

**Issue by michygeek** [beriain/PolarClock#4]
#### Expected behavior
Clicking on `setting` should take me to available setting to suit my specifications 

#### Actual behavior
When i clicked on `setting` Nothing shows up/pops up 

#### How to reproduce
1. Download [polar clock](https://f-droid.org/packages/eu.polarclock/)

2. Launch and click on the 3 Vertical dot 

3. Then click on `Settings`

* Device Used: Tecno Droid-pad 8ll 
* Operating system: Android version: 5.1

App Version: Version 1.4.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=LqVyrLwFhL0
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tykee/bug-foung-on-settings-button">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by beriain** [comment]
Hi!

You say you are using version 1.4.1, but the logo in the video is previous to version 1.4. I made the menu slightly bigger starting from 1.4 beacause it was hard to click sometimes.

Could you verify you are using latest version?

Thanks

**Comment by mikini** [comment]
Hi.
I just installed 1.4.1 from f-droid (got a screenshot of version on fd, but github won't let me upload right now) on stock Samsung Galaxy S7 (Android 7.0) and see similar behaviour. Here, however the navigation application ZANavi is opened when selecting both Settings and About.

Just for the experiment I tried uninstalling ZANavi and now the PolarClock Settings and About is shown as expected.

**Comment by beriain** [comment]
Thanks for reporting this. I can reproduce it with ZANavi also, but I think I have solved it. I'm going to publish a new version, please check it solves this problem also for you.

**Comment by beriain** [comment]
The new version (1.4.2) has been published in F-Droid, and it solves this issue.

**Comment by mikini** [comment]
I can confirm, 1.4.2 works for me too.
