### ISSUE TITLE
Bug found in about 

### ISSUE THREAD

**Issue by michygeek** [beriain/PolarClock#5]
#### Expected behavior
Clicking on `about` should provide all the necessary details about the maker of the application

#### Actual behavior
When i clicked on `about` it brings uncertainty message and take me to my mobile WPS reader 

#### How to reproduce
1. Download [Polar Clock](https://f-droid.org/packages/eu.polarclock/)

2. Click on the 3 vertical and click on edit 

* Device used: Tecno Droid-pad 8ll 
* Operating system: Android Version: 5.1

App version:1.4.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=3Y9wKbfxPEw
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tykee/bug-found-in-about">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by beriain** [comment]
This is quite strange, the About menu button is just an HTML ```div``` inside an ```a``` link to a file in ```assets``` folder.

I can't reproduce it at all. Do you have the latest system webview update installed?

**Comment by beriain** [comment]
Ok, according to [this](https://java.wekeepcoding.com/article/11940337/WPS+Office+hijacking+Webview+of+my+App), [this](https://stackoverflow.com/questions/36070965/wps-office-take-the-html-opened-file-from-chrome-when-pressing-a-link) and [this](https://stackoverflow.com/questions/29130690/the-file-must-have-been-renamed-moved-or-deleted-warning-in-android-webview), it seems WPS office hijacks all links in any webview.

They give some workarounds there, but I'm not 100% sure if them work. If you want, I can try to build a test .apk whit the workarounds and if they work for you, I will release a new version with them.

**Comment by beriain** [comment]
The new version (1.4.2) has been published in F-Droid, and I believe it solves this issue.
